
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../i18n";
import { Providers } from "./Providers";
import { Button, Space, Layout, Typography, Flex } from 'antd';
import HeaderComponent from "../components/Header";
import ContentComponent from "../components/Content";
const { Title } = Typography;
const { Header, Content, Footer } = Layout;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={false}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers >
          <Layout style={{ minHeight: '100vh' }}>
        
            <HeaderComponent />
            <ContentComponent>
                            {children}

            </ContentComponent>
          </Layout>
          {/* {children} */}

        </Providers >
        {/* {children} */}
      </body>
    </html>
  );
}
